Added operating buttons in sidebar
AnnMurr/fe-46-ANNA_MURINA pull request #11
Opened 2023-02-16 14:06 UTC by AnnMurr

2023-02-17 08:37 UTC, UladTeachMeSkills requested changes

2023-02-17 08:37 UTC, UladTeachMeSkills commented on axit-project/core/index.js
> +})
sidebarBtn.addEventListener('click', e => onBorgerClick(e)) Вот так будет работать

2023-02-17 08:37 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                <ul class="sidebar__nav" id="sidebar__nav">
Можно обойтись без id

2023-02-17 08:37 UTC, UladTeachMeSkills commented on axit-project/core/index.js
> +const sidebarBtn = document.getElementById("sidebar__nav");
document.querySelector(".sidebar__nav");

2023-02-17 14:18 UTC, AnnMurr commented on axit-project/core/index.js
> +})
оно, кстати, работает и так и так

2023-02-19 15:21 UTC, UladTeachMeSkills approved these changes

2023-02-20 12:38 UTC, merged