Added files
AnnMurr/fe-46-ANNA_MURINA pull request #21
Opened 2023-02-26 17:58 UTC by AnnMurr

2023-02-27 08:57 UTC, UladTeachMeSkills requested changes
Здорово! Молодец)

2023-02-27 08:57 UTC, UladTeachMeSkills commented on Lesson-9/task-3/aurora.html
> +                            <a href="./audio/aurora.mp3"></a>
Для чего ссылка внутри аудио?

2023-02-27 08:57 UTC, UladTeachMeSkills commented on Lesson-9/task-3/forest.html
> +                            <a href="./audio/forest.mp3"></a>
same

2023-02-27 08:57 UTC, UladTeachMeSkills commented on Lesson-9/task-3/index.html
> +                    <div class="menu__wrap">
Наверное это список)

2023-02-27 08:57 UTC, UladTeachMeSkills commented on Lesson-9/task-3/jungle.html
> +                            <a href="./audio/jungle.mp3"></a>
same

2023-02-27 08:57 UTC, UladTeachMeSkills commented on Lesson-9/task-3/sea.html
> +                            <a href="./audio/sea.mp3"></a>
same

2023-02-27 08:57 UTC, UladTeachMeSkills commented on Lesson-9/task-3/waterfall.html
> +                            <a href="./audio/waterfall.mp3"></a>
same

2023-02-27 10:25 UTC, AnnMurr commented on Lesson-9/task-3/waterfall.html
> +                            <a href="./audio/waterfall.mp3"></a>
это чтобы можно было скачать аудио, вдруг кому-нибудь захочется)

2023-02-28 09:20 UTC, UladTeachMeSkills approved these changes

2023-02-28 09:20 UTC, UladTeachMeSkills commented on Lesson-9/task-4/index.html
> +        <div class="container">,
Оу май

2023-02-28 10:52 UTC, UladTeachMeSkills approved these changes

2023-02-28 10:58 UTC, merged