Homework/banner
AnnMurr/fe-46-ANNA_MURINA pull request #6
Opened 2023-02-08 19:26 UTC by AnnMurr

2023-02-08 20:29 UTC, UladTeachMeSkills requested changes

2023-02-08 20:29 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                        <li>Features</li>
Оберни текст в ссылку с адресом href="#I'd твоей соответствующей секции"
Каждой секции добавь соответствующий ей индивидуальный id

2023-02-08 20:29 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                            <div class="social__icon">
Сделай ссылками

2023-02-08 20:29 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                            </div>
Непонятно откуда взялся закрывающий тэг

2023-02-08 20:29 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                        </div>
Непонятно откуда взялся закрывающий тэг

2023-02-09 08:04 UTC, AnnMurr commented on axit-project/index.html
> +                            </div>
это от contacts__user

2023-02-09 08:05 UTC, AnnMurr commented on axit-project/index.html
> +                        </div>
а это от contacts__inputs

2023-02-09 10:39 UTC, UladTeachMeSkills approved these changes

2023-02-10 11:46 UTC, merged